QuaZip: QuaAdler32 Class Reference
QuaAdler32 Class Reference
Adler32 checksum.
#include <quazip/quaadler32.h>
Public Member Functions
quint32 calculate (const QByteArray &data) override
Calculates the checksum for data.
void reset () override
Resets the calculation on a checksun for a stream.
void update (const QByteArray &buf) override
Updates the calculated checksum for the stream.
quint32 value () override
Value of the checksum calculated for the stream passed throw update().
virtual quint32 calculate (const QByteArray &data)=0
Calculates the checksum for data.
virtual void reset ()=0
Resets the calculation on a checksun for a stream.
virtual void update (const QByteArray &buf)=0
Updates the calculated checksum for the stream.
virtual quint32 value ()=0
Value of the checksum calculated for the stream passed throw update().
Detailed Description
Adler32 checksum.
This class wrappers the adler32 function with the QuaChecksum32 interface. See QuaChecksum32 for more info.
Member Function Documentation
calculate()
quint32 QuaAdler32::calculate (const QByteArray & data) override virtual
Calculates the checksum for data.
data source data
Returns
data checksum
This function has no efect on the value returned by value().
Implements QuaChecksum32.
References QByteArray::data(), and QByteArray::size().
reset()
void QuaAdler32::reset () override virtual
Resets the calculation on a checksun for a stream.
Implements QuaChecksum32.
update()
void QuaAdler32::update (const QByteArray & buf) override virtual
Updates the calculated checksum for the stream.
buf next portion of data from the stream
Implements QuaChecksum32.
References QByteArray::data(), and QByteArray::size().
value()
quint32 QuaAdler32::value () override virtual
Value of the checksum calculated for the stream passed throw update().
Returns
checksum
Implements QuaChecksum32.
The documentation for this class was generated from the following files:
quazip/quaadler32.h
quazip/quaadler32.cpp