######################################################################
# Automatically generated by qmake (2.00a) Sun Jun 26 21:12:22 2005
######################################################################

TEMPLATE = app
CONFIG += qt warn_on release
QT -= gui
DEPENDPATH += .
INCLUDEPATH += . ../..
LIBS += -L../../quazip -lquazip

# Input
SOURCES += main.cpp
