name: Reusable build workflow

on:
  workflow_call:
    inputs:
      os_version:
        required: true
        type: string
      qt_version:
        required: true
        type: string
      shared:
        required: false
        default: "ON"
        type: string
      zlib_const:
        required: false
        default: "OFF"
        type: string
      runs_on:
        required: true
        type: string
    secrets:
        GH_TOKEN:
            required: false

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # All aqt options: https://ddalcino.github.io/aqt-list-server/
  BUILD_TYPE: Release
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    # Ubuntu 20.04 is EOL and being removed from runners so we use a container instead
    runs-on: ${{ inputs.runs_on != 'ubuntu-20.04' && inputs.runs_on || 'ubuntu-22.04' }}
    container: ${{ inputs.runs_on == 'ubuntu-20.04' && format('ubuntu:{0}', inputs.os_version) || '' }}
    name: Build-${{ inputs.runs_on }}-Qt-${{ inputs.qt_version }}-shared-${{ inputs.shared }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install missing packages from container
        if: inputs.runs_on == 'ubuntu-20.04'
        run: |
           apt-get update &&
           apt-get install -y --no-install-recommends \
           libc6

      - name: Install Qt6
        if: "startsWith(inputs.qt_version, '6.')"
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ inputs.qt_version }}
          cache: 'true'
          cache-key-prefix: ${{ runner.os }}-Qt-Cache-${{ inputs.qt_version }}
          dir: ${{ github.workspace }}/Qt
          modules: 'qt5compat'
          install-deps: ${{ inputs.runs_on != 'ubuntu-20.04' && 'true' || 'nosudo' }}

      - name: Install Qt5
        if: "startsWith(inputs.qt_version, '5.')"
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ inputs.qt_version }}
          cache: 'true'
          cache-key-prefix: ${{ runner.os }}-Qt-Cache-${{ inputs.qt_version }}
          dir: ${{ github.workspace }}/Qt
          install-deps: ${{ inputs.runs_on != 'ubuntu-20.04' && 'true' || 'nosudo' }}

      - name: Install libraries (Linux Only)
        if: contains(inputs.runs_on, 'ubuntu')
        run: |
          sudo apt-get update &&
          sudo apt-get install -y --no-install-recommends \
          zlib1g-dev libbz2-dev

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -DBUILD_SHARED_LIBS=${{ inputs.shared }} -DQUAZIP_ENABLE_TESTS=ON -DZLIB_CONST=${{ inputs.zlib_const }} -B "${{github.workspace}}/build"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        env:
          TEST_CROSS_PLATFORM: "true"
        run: "ctest --verbose"

      - name: Upload cp.zip to GitHub Actions Storage
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          overwrite: true
          name: "${{ inputs.runs_on }}_qt${{ inputs.qt_version }}_shared${{ inputs.shared }}_cp.zip"
          path: build/quazip/cp.zip

